#!/bin/bash

GT=$(git rev-parse --show-toplevel)

cat ~/.config/git/inits/hooks/.gitignore.go >> $GT/.gitignore
sed -i '0,/^# --- --- --- プロジェクト毎の設定 --- --- --- #$/{
  /^# --- --- --- プロジェクト毎の設定 --- --- --- #$/d
}' $GT/.gitignore
cp -i ~/.config/git/inits/hooks/.golangci.yml $GT/.golangci.yml
cp -ri ~/.config/git/inits/hooks/.github/ $GT/./

echo -e 'STEP 1:\n git add $GT/changelog.config.js\n'
echo -e 'STEP2:\n git cz\n  setting\n  changelog.config.js を更新\n'
